const express = require('express');
const logger = require('morgan');
const bodyParser = require('body-parser');
const expressValidator = require('express-validator');
var cors = require('cors');
const routeV1 = require('./routes/index');
const app = express();   
var cors = require('cors')
app.use(cors())

// *** cross domain requests *** //

/*
app.use((req, res, next) => {
  res.header('Access-Control-Allow-Origin', '*');
  res.header('Access-Control-Allow-Methods', 'GET, POST, PUT, DELETE');
  res.header('Access-Control-Allow-Headers', 'Origin, X-Requested-With, Content-Type, Authorization');
  next();
});
*/

app.disable('x-powered-by');
app.use(logger('dev'));
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: false }));
app.use(expressValidator()); // required for Express-Validator

app.use('/api/v1', routeV1);

// catch 404 and forward to error handler
app.use((req, res, next) => {
  const err = new Error('No Encontrado');
  err.status = 404;
  next(err);
});

// error handler
app.use((err, req, res, next) => {
  if (!err) return next();
  // set locals, only providing error in development
  res.locals.message = err.message;
  res.locals.error = req.app.get('env') === 'development' ? err : {};
  return res.status(err.status || 500).json({ error: true, message: err.message || [] });
});

process.on('uncaughtException', (err) => {
  console.error('uncaughtException: ', err);
  console.error(err.stack);
  process.exit(1);
});


module.exports = app;
